### ISSUE TITLE
Luis Febrero (94.23.214.128)

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Bridge#10]
На торговом счету (PHP-Demo 938586 pw_user1) открывается BUY LIMIT, SELL LIMIT, на контрольном (PHP-Demo 938588 pw_user1) и на клиринге (FIX, но видно на PHP-Demo 10051, Abc123) открывается market order. Если BUY STOP, SELL STOP - Off quotes

**Comment by JuliviMig** [comment]
для всех  вариантов  кроме источника  BJF_FIX не  копирую  отложенные  и  SL  TP
