### ISSUE TITLE
Луис - Currenex reboot

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Bridge#2]
При старте 10.12.17 FIX счет не подключился, м.б. по случаю воскресенья. Бридж вышел на попытки перезагрузки, и на них крутился до 12.12, пока не перезагрузили его самого
10.12.2017 22:42:58 MT4_SERVER_WL1  ERROR Error  connect server -5
10.12.2017 22:42:58 MT4_SERVER_CTRL Start MT4_SERVER_CTRL
10.12.2017 22:42:58 MT4_SERVER_CTRL IdentUser  36
10.12.2017 22:42:58 MT4_SERVER_CTRL ListUSER.Count  0
10.12.2017 22:42:58 MT4_SERVER_CTRL ERROR Error  connect server -5
10.12.2017 22:42:58 FIX_CLEARING    Start FIX_CLEARING
10.12.2017 22:42:58 FIX_CLEARING    CreateConnect (1)
10.12.2017 22:42:58 FIX_CLEARING    Error  Connect timed out.
10.12.2017 22:42:58 FIX_CLEARING    Load users 1
10.12.2017 22:42:58 Finish BRIDGE_SOURCE
10.12.2017 22:42:58 Start  server  socket Time port 32863
10.12.2017 22:42:58 Start  server  socket port PAMM 32864
10.12.2017 22:42:58 Start  server  socket port 32865
10.12.2017 22:42:58 FIX_CLEARING    ERROR CurrenexVolume ErrorConnect
10.12.2017 22:42:58 FIX_CLEARING    Reboot CurrenexVolume 0
10.12.2017 22:42:58 FIX_CLEARING    Reboot CurrenexError 0
10.12.2017 22:42:58 FIX_CLEARING    ERROR Error connect volume
10.12.2017 22:42:58 FIX_CLEARING    Reboot CurrenexVolume 0
10.12.2017 22:42:58 FIX_CLEARING    Reboot CurrenexError 1
10.12.2017 22:42:59 FIX_CLEARING    Reboot CurrenexVolume 0
10.12.2017 22:42:59 FIX_CLEARING    Reboot CurrenexError 2

**Comment by JuliviMig** [comment]
10.12.2017 22:42:58 MT4_SERVER_WL1 ERROR Error connect server -5
RET_OLD_VERSION        = 5;        // old client terminal
  странно.  Воспроизвести  бы.  Клиринг  видно  что  законектился
